description: Enable emuNAND

patches:
    patch1.bin:
        type: Memory
        subtype: NATIVE_FIRM
        options:
            - emunand
        variables:
            - sdmmc
        versions:
            o3ds:
                0x5E:
                    - 0x080D8A70
                0x5C:
                    - 0x080D8A70
                0x58:
                    - 0x080D8A70
                0x56:
                    - 0x080D8A70
                0x52:
                    - 0x080D8A70
                0x50:
                    - 0x080D8A50
                0x4C:
                    - 0x080D8A30
                0x4B:
                    - 0x080D8A30
                0x49:
                    - 0x080D8670
                0x40:
                    - 0x080D8670
                0x3F:
                    - 0x080D8670
                0x38:
                    - 0x080D8670
                0x37:
                    - 0x080D84F0
                0x30:
                    - 0x080D8430
                0x2E:
                    - 0x080D8430
                0x2A:
                    - 0x080D84B0
                0x29:
                    - 0x080D84B0
                0x26:
                    - 0x080D95B0
                0x25:
                    - 0x080D9690
                0x1F:
                    - 0x080D8CD0
                0x1D:
                    - 0x27FC6050
                0x18:
                    - 0x080D91D8
            n3ds:
                0x2F:
                    - 0x080F0B10
                0x2D:
                    - 0x080F0AF0
                0x21:
                    - 0x080F0AF0
                0x1F:
                    - 0x080F0AD0
                0x1B:
                    - 0x080F0AB0
                0x0F:
                    - 0x080D86F0

    patch2.bin:
        type: NATIVE_FIRM
        versions:
            o3ds:
                0x5E: 0x0801B564
                0x5C: 0x0801B564
                0x58: 0x0801B564
                0x56: 0x0801B564
                0x52: 0x0801B564
                0x50: 0x0801B564
                0x4C: 0x0801B564
                0x4B: 0x0801B564
                0x49: 0x0801B564
                0x40: 0x0801B564
                0x3F: 0x0801B564
                0x38: 0x0801B564
                0x37: 0x0801B564
                0x30: 0x0801B568
                0x2E: 0x0801B568
                0x2A: 0x0801B568
                0x29: 0x0801B568
                0x26: 0x0801A568
                0x25: 0x0801A568
                0x1F: 0x0801B568
                0x1D: 0x0801B568
                0x18: 0x0801B568
            n3ds:
                0x2F: 0x0801B3D4
                0x2D: 0x0801B3D4
                0x21: 0x0801B3D4
                0x1F: 0x0801B3D4
                0x1B: 0x0801B3D4
                0x0F: 0x0801B3D4

    patch3.bin:
        type: NATIVE_FIRM
        memory:
            patch: patch1.bin
            variable: mem
        versions:
            o3ds:
                0x5E: 0x08077C48
                0x5C: 0x08077C34
                0x58: 0x08077C30
                0x56: 0x08077BF0
                0x52: 0x08077BF0
                0x50: 0x08077B5C
                0x4C: 0x08077B40
                0x4B: 0x08077B40
                0x49: 0x0807882C
                0x40: 0x0807877C
                0x3F: 0x0807877C
                0x38: 0x08078724
                0x37: 0x0807868C
                0x30: 0x0807840C
                0x2E: 0x08078408
                0x2A: 0x080784C4
                0x29: 0x080784C4
                0x26: 0x08078460
                0x25: 0x080783F8
                0x1F: 0x08078C30
                0x1D: 0x08078C30
                0x18: 0x08078852
            n3ds:
                0x2F: 0x08077C44
                0x2D: 0x08077C30
                0x21: 0x08077BEC
                0x1F: 0x08077B5C
                0x1B: 0x08077B40
                0x0F: 0x0807877C

    patch4.bin:
        type: NATIVE_FIRM
        memory:
            patch: patch1.bin
            variable: mem
        versions:
            o3ds:
                0x5E: 0x08077C88
                0x5C: 0x08077C74
                0x58: 0x08077C70
                0x56: 0x08077C30
                0x52: 0x08077C30
                0x50: 0x08077B9C
                0x4C: 0x08077B80
                0x4B: 0x08077B80
                0x49: 0x0807886C
                0x40: 0x080787BC
                0x3F: 0x080787BC
                0x38: 0x08078764
                0x37: 0x080786CC
                0x30: 0x0807844C
                0x2E: 0x08078448
                0x2A: 0x08078504
                0x29: 0x08078504
                0x26: 0x080784A0
                0x25: 0x08078438
                0x1F: 0x08078C70
                0x1D: 0x08078C70
                0x18: 0x08078892
            n3ds:
                0x2F: 0x08077C84
                0x2D: 0x08077C70
                0x21: 0x08077C2C
                0x1F: 0x08077B9C
                0x1B: 0x08077B80
                0x0F: 0x080787BC
